# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 31792ec52518ca99a93e021b6c369f455ede0331ee08d81bdd52675b263fae56342c3d4c08ea43cfe2cddc928834e56158a892d02d207da3d50af665a6cede83

test:
  secret_key_base: df886fed747037aab1ed35487bee4f93f62d8b2aa94f916ad0b7683bd4f56bff18120b0b5a0b2852c6d661c05473040fce93137d41533250940a7a655dd6da0b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
